language: node_js
node_js: 
  - "node"
  - "lts/*"

before_install:

install: 
  - "npm install"
  
script:
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash npm run build fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then npm run test fi'
  
  
